# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "tim lockridge"
description: > # this means to ignore newlines until "email:"
   writer, reader, professor

email: timlockridge@gmail.com
#blog logo
logo: "/assets/images/tim.jpg"
# blog cover
cover: "/assets/images/cover1.gif"

name: 'Tim Lockridge'
author: 'Tim Lockridge'
author_image: "/assets/images/author.jpg"

permalink: /blog/:categories/:year/:month/:day/:title.html
paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/timlockridge
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/timlockridge
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
